# Generated by Django 4.2.7 on 2023-11-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Businessapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(default=0, max_length=50)),
                ('description', models.TextField()),
                ('origin', models.CharField(max_length=50)),
            ],
        ),
    ]
